// one-off: node fetch-images.mjs
// Finds a Wikipedia thumbnail per word, downloads it into imgs/, writes images.js
// mapping word → local file. Re-run only when VOCAB gains new words (skips existing).
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';

const here = p => new URL(p, import.meta.url);
const src = readFileSync(here('game.js'), 'utf8');
const VOCAB = eval(src.match(/const VOCAB = (\[[\s\S]*?\n\]);/)[1]);
mkdirSync(here('imgs'), { recursive: true });

const sleep = ms => new Promise(r => setTimeout(r, ms));
const strip = s => s.split(' /')[0].split(' (')[0]
  .replace(/^(le |la |les |l'|el |los |las |una |un |en )/i, '').trim();

async function get(url) {
  for (let t = 1; t <= 3; t++) {
    try {
      const r = await fetch(url, { headers: { 'user-agent': 'parole-vocab-game/1.0 (personal project)' } });
      if (r.status === 429) { await sleep(3000 * t); continue; }
      return r.ok ? r : null;
    } catch { await sleep(1000); }
  }
  return null;
}
async function thumbUrl(lang, term) {
  const r = await get(`https://${lang}.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(term)}`);
  return r ? (await r.json()).thumbnail?.source || null : null;
}

const images = {};
let done = 0;
for (const v of VOCAB) {
  const slug = v.fr.normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^a-z]+/gi, '-');
  const existing = ['jpg', 'png', 'webp', 'gif'].map(e => `imgs/${slug}.${e}`).find(f => existsSync(here(f)));
  if (existing) {
    images[v.fr] = existing;
    console.log(`${++done}/${VOCAB.length} ${v.fr} → ${existing} (cached)`);
    continue;
  }
  const url = await thumbUrl('fr', strip(v.fr)) || await thumbUrl('es', strip(v.es));
  if (url) {
    const r = await get(url);
    if (r) {
      const ext = url.match(/\.(jpe?g|png|gif|webp)/i)?.[1].toLowerCase().replace('jpeg', 'jpg') || 'jpg';
      const file = `imgs/${slug}.${ext}`;
      writeFileSync(here(file), Buffer.from(await r.arrayBuffer()));
      images[v.fr] = file;
    }
  }
  console.log(`${++done}/${VOCAB.length} ${v.fr} → ${images[v.fr] || '—'}`);
  await sleep(100);
}

writeFileSync(here('images.js'),
  '// generated by fetch-images.mjs — do not edit by hand\nconst IMAGES = ' +
  JSON.stringify(images, null, 1) + ';\n');
console.log(`done: ${Object.keys(images).length}/${VOCAB.length} words have a local image`);
