// one-off: node gen-images.mjs
// Generates a flat illustration (free, Pollinations/FLUX) for every word that has no
// image in imgs/ — except opinion connectors, which stay text-only on purpose.
// Skips existing files, so it's re-runnable; delete a bad image and re-run to redo it.
// At the end, rebuilds images.js purely from what's on disk (wiki + generated).
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';

const here = p => new URL(p, import.meta.url);
const src = readFileSync(here('game.js'), 'utf8');
const VOCAB = eval(src.match(/const VOCAB = (\[[\s\S]*?\n\]);/)[1]);
const sleep = ms => new Promise(r => setTimeout(r, ms));
mkdirSync(here('imgs'), { recursive: true });

const slugOf = fr => fr.normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^a-z]+/gi, '-');
const onDisk = slug => ['jpg', 'png', 'webp', 'gif'].map(e => `imgs/${slug}.${e}`).find(f => existsSync(here(f)));

const todo = VOCAB.filter(v => v.theme !== 'opinion' && !onDisk(slugOf(v.fr)));
console.log(`generating ${todo.length} images…`);
let ok = 0, fail = 0;
for (const v of todo) {
  const prompt = `simple flat vector illustration for a language learning flashcard, ` +
    `clearly depicting the concept "${v.es}" (french: ${v.fr}), everyday life scene in France, ` +
    `soft colors, minimal, no text, no words, no letters, no numbers`;
  const url = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=512&height=320&nologo=true&seed=42`;
  try {
    const r = await fetch(url, { signal: AbortSignal.timeout(120000) });
    const buf = Buffer.from(await r.arrayBuffer());
    if (!r.ok || buf.length < 5000) throw new Error('bad response ' + r.status);
    writeFileSync(here(`imgs/${slugOf(v.fr)}.jpg`), buf);
    console.log(`${++ok + fail}/${todo.length} ${v.fr} ✓`);
  } catch (e) {
    fail++;
    console.log(`${ok + fail}/${todo.length} ${v.fr} ✗ ${e.message}`);
  }
  await sleep(1500);
}

const images = {};
for (const v of VOCAB) {
  const f = onDisk(slugOf(v.fr));
  if (f) images[v.fr] = f;
}
writeFileSync(here('images.js'),
  '// generated by fetch-images.mjs / gen-images.mjs — do not edit by hand\nconst IMAGES = ' +
  JSON.stringify(images, null, 1) + ';\n');
console.log(`done: ${ok} generated, ${fail} failed — images.js now maps ${Object.keys(images).length}/${VOCAB.length} words`);
