// generated — do not edit by hand
const IMAGES = {
 "l'entreprise": "imgs/l-entreprise.jpg",
 "le salaire": "imgs/le-salaire.jpg",
 "l'entretien": "imgs/l-entretien.jpg",
 "le patron": "imgs/le-patron.jpg",
 "la réunion": "imgs/la-reunion.jpg",
 "le congé": "imgs/le-conge.jpg",
 "la formation": "imgs/la-formation.jpg",
 "embaucher": "imgs/embaucher.jpg",
 "démissionner": "imgs/demissionner.jpg",
 "le loyer": "imgs/le-loyer.jpg",
 "le bail": "imgs/le-bail.jpg",
 "le propriétaire": "imgs/le-proprietaire.jpg",
 "le locataire": "imgs/le-locataire.jpg",
 "le quartier": "imgs/le-quartier.jpg",
 "les charges": "imgs/les-charges.jpg",
 "déménager": "imgs/demenager.jpg",
 "meublé": "imgs/meuble.jpg",
 "la colocation": "imgs/la-colocation.jpg",
 "le médecin": "imgs/le-medecin.jpg",
 "l'ordonnance": "imgs/l-ordonnance.png",
 "la douleur": "imgs/la-douleur.jpg",
 "l'assurance": "imgs/l-assurance.jpg",
 "le traitement": "imgs/le-traitement.jpg",
 "guérir": "imgs/guerir.jpg",
 "la salle d'attente": "imgs/la-salle-d-attente.png",
 "le vaccin": "imgs/le-vaccin.jpg",
 "blessé": "imgs/blesse.jpg",
 "le dossier": "imgs/le-dossier.jpg",
 "le formulaire": "imgs/le-formulaire.jpg",
 "la demande": "imgs/la-demande.jpg",
 "le délai": "imgs/le-delai.jpg",
 "la mairie": "imgs/la-mairie.jpg",
 "le justificatif": "imgs/le-justificatif.jpg",
 "la carte de séjour": "imgs/la-carte-de-sejour.jpg",
 "renouveler": "imgs/renouveler.jpg",
 "signer": "imgs/signer.jpg",
 "le compte": "imgs/le-compte.jpg",
 "le virement": "imgs/le-virement.jpg",
 "les frais": "imgs/les-frais.jpg",
 "l'impôt": "imgs/l-impot.jpg",
 "le prêt": "imgs/le-pret.jpg",
 "la facture": "imgs/la-facture.jpg",
 "économiser": "imgs/economiser.jpg",
 "dépenser": "imgs/depenser.jpg",
 "le reçu": "imgs/le-recu.jpg",
 "l'inscription": "imgs/l-inscription.jpg",
 "la bourse": "imgs/la-bourse.jpg",
 "les courses": "imgs/les-courses.jpg",
 "l'horaire": "imgs/l-horaire.gif",
 "la météo": "imgs/la-meteo.png",
 "les embouteillages": "imgs/les-embouteillages.jpg",
 "la grève": "imgs/la-greve.jpg",
 "le chômage": "imgs/le-chomage.jpg",
 "le contrat": "imgs/le-contrat.jpg",
 "le poste": "imgs/le-poste.jpg",
 "le CV": "imgs/le-CV.jpg",
 "l'équipe": "imgs/l-equipe.jpg",
 "le syndicat": "imgs/le-syndicat.jpg",
 "la retraite": "imgs/la-retraite.jpg",
 "gérer": "imgs/gerer.jpg",
 "l'immeuble": "imgs/l-immeuble.gif",
 "l'ascenseur": "imgs/l-ascenseur.jpg",
 "la pièce": "imgs/la-piece.jpg",
 "le chauffage": "imgs/le-chauffage.jpg",
 "l'étage": "imgs/l-etage.png",
 "louer": "imgs/louer.jpg",
 "le voisinage": "imgs/le-voisinage.png",
 "la maladie": "imgs/la-maladie.jpg",
 "la fièvre": "imgs/la-fievre.jpg",
 "le rhume": "imgs/le-rhume.png",
 "la pharmacie": "imgs/la-pharmacie.jpg",
 "le comprimé": "imgs/le-comprime.jpg",
 "les urgences": "imgs/les-urgences.png",
 "l'infirmier": "imgs/l-infirmier.jpg",
 "tousser": "imgs/tousser.jpg",
 "la grippe": "imgs/la-grippe.jpg",
 "le passeport": "imgs/le-passeport.jpg",
 "la pièce d'identité": "imgs/la-piece-d-identite.jpg",
 "la photocopie": "imgs/la-photocopie.jpg",
 "la naissance": "imgs/la-naissance.jpg",
 "la signature": "imgs/la-signature.png",
 "la banque": "imgs/la-banque.jpg",
 "le distributeur": "imgs/le-distributeur.jpg",
 "les espèces": "imgs/les-especes.png",
 "la carte bancaire": "imgs/la-carte-bancaire.jpg",
 "le budget": "imgs/le-budget.jpg",
 "gratuit": "imgs/gratuit.jpg",
 "cher": "imgs/cher.png",
 "le retrait": "imgs/le-retrait.jpg",
 "l'élève": "imgs/l-eleve.jpg",
 "la moyenne": "imgs/la-moyenne.png",
 "le concours": "imgs/le-concours.jpg",
 "la lecture": "imgs/la-lecture.jpg",
 "l'écriture": "imgs/l-ecriture.jpg",
 "la traduction": "imgs/la-traduction.jpg",
 "enseigner": "imgs/enseigner.jpg",
 "la boulangerie": "imgs/la-boulangerie.jpg",
 "le marché": "imgs/le-marche.jpg",
 "la poubelle": "imgs/la-poubelle.jpg",
 "le ménage": "imgs/le-menage.jpg",
 "le repas": "imgs/le-repas.jpg",
 "le loisir": "imgs/le-loisir.jpg",
 "la randonnée": "imgs/la-randonnee.jpg",
 "le covoiturage": "imgs/le-covoiturage.jpg",
 "la file d'attente": "imgs/la-file-d-attente.jpg",
 "quotidien": "imgs/quotidien.jpg",
 "devoir": "imgs/devoir.jpg",
 "savoir": "imgs/savoir.jpg",
 "connaître": "imgs/connaitre.jpg",
 "comprendre": "imgs/comprendre.jpg"
};
